"""
These items are assets in the data, but not really items that we would want in the wiki, so they can be easily excluded from various scripts.
"""
SKIP_ITEMS = [
    "aegis",
    "alchemy bundle",
    "alien chair",
    "amethystnode",
    "ancient nel'varian text",
    "angler's box",
    "animal feeder",
    "arched bridge decor",
    "archeology bundle",
    "arena chest",
    "bones bundle",
    "bonus attack damage",
    "bonus movement speed",
    "bonus spell damage",
    "breakable pot",
    "breath stone",
    "bridge customization kit",
    "brinestone deeps classic record",
    "brinestone deeps general store record",
    "brinestone teleportation spell",
    "brinestonedeepsrock1x1_green",
    "brinestonedeepsrock1x1_grey",
    "brinestonedeepsrock1x1_yellow",
    "brinestonedeepsrock2x2_green",
    "brinestonedeepsrock2x2_grey",
    "brinestonedeepsrock2x2_yellow",
    "broken branches",
    "broken cobblestone",
    "bundle aquarium bigtank",
    "bundle aquarium fall",
    "bundle aquarium nelvari",
    "bundle aquarium spring",
    "bundle aquarium summer",
    "bundle aquarium winter",
    "bundle aquarium withergate",
    "candyfloss machine",
    "catch of the day",
    "citrine node",
    "claude apple tree",
    "cobble stone bridge decor",
    "combat bundle",
    "common fish",
    "dead crop",
    "diamondnode",
    "dizzite node",
    "dizzy rock node",
    "dragon chest",
    "dragon chest one time",
    "dragon trap",
    "dungeon chest",
    "dynus altar rareitems",
    "earth crystal forageable",
    "elven blueberry tree",
    "elven bridge decor",
    "elven eyes",
    "elven hardwood tree",
    "elven heavystone node",
    "elven peach tree",
    "elven raspberry tree",
    "elven stone node",
    "elven strawberry tree",
    "epic fish",
    "even window trio",
    "expert crafter",
    "explorer's box",
    "fall crops bundle",
    "fallen log",
    "farmer's box",
    "farming slot maker",
    "fire beam",
    "fire crystal forageable",
    "fire fruit seeds",
    "firebolt gift",
    "fishing bundle",
    "flames and ashes chest",
    "floor 1 dungeon key",
    "floor 10 dungeon key",
    "floor 15 dungeon key",
    "floor 20 dungeon key",
    "floor 25 dungeon key",
    "floor 5 dungeon key",
    "flowers bundle",
    "forageable chest",
    "forest sleeping monster",
    "forked road sleeping monster",
    "four region's thank you letter",
    "gembundle",
    "geode bundle",
    "geode muncher",
    "golden bundle",
    "gorwin's gift",
    "hard deadwood tree",
    "havenitenode",
    "heavystone node",
    "hot chocolate machine",
    "house customization kit",
    "hu",
    "hungry slime bundle one",
    "hungry slime bundle three",
    "hungry slime bundle two",
    "ink puddle",
    "kitty gift",
    "krusty rock node",
    "lapis node",
    "leaf gift",
    "legendary fish",
    "letter from lucia",
    "miracle",
    "modern bridge decor",
    "money bag forageable",
    "moneybundle",
    "monster bridge decor",
    "music note gift",
    "nathaniel chest",
    "origins of dynus and shadows_ book i",
    "origins of dynus and shadows_ book ii",
    "origins of dynus and shadows_ book iii",
    "origins of dynus and shadows_ book iv",
    "origins of dynus and shadows_ book v",
    "origins of sun haven and elios_ book i",
    "origins of sun haven and elios_ book ii",
    "origins of sun haven and elios_ book iii",
    "origins of sun haven and elios_ book iv",
    "origins of sun haven and elios_ book v",
    "origins of the grand tree and nivara_ book i",
    "origins of the grand tree and nivara_ book ii",
    "origins of the grand tree and nivara_ book iii",
    "origins of the grand tree and nivara_ book iv",
    "origins of the grand tree and nivara_ book v",
    "peter bomb fish bundle",
    "pile of snow",
    "pilot targeting window",
    "pirated thick coral display",
    "pixie dust",
    "player farm nelvari stone node",
    "player farm stone node",
    "player farm withergate stone node",
    "poorly wrapped gift",
    "powerful sun display",
    "primal nature",
    "pyre",
    "rare fish",
    "rock 'n' roll chest",
    "rock fruit seeds",
    "rock1b",
    "rock1c",
    "rock1d",
    "rock2b",
    "rock2c",
    "rock2d",
    "rock3b",
    "rock3c",
    "rock3d",
    "rock4b",
    "rock4c",
    "rock4d",
    "rock5b",
    "rock5c",
    "rock5d",
    "rock6b",
    "rock6c",
    "rock6d",
    "rock7b",
    "rock7c",
    "rock7d",
    "rubynode",
    "sapphirenode",
    "shang chest",
    "smoke",
    "snaccoon block farm",
    "snaccoon costume chest",
    "snaccoon town hall",
    "snacoon beach bridge",
    "snacoon beach pier",
    "snacoon beach transition",
    "snacoon farm",
    "snacoon foresta",
    "snacoon forestf",
    "snacoon mines20a",
    "snacoon mines40a",
    "snacoon nelvari",
    "snacoon quarry",
    "snacoon quarry transition",
    "snacoon right outskirts",
    "snacoon wheat field",
    "snowy observation window",
    "sock kites",
    "solon order form",
    "soup bundle",
]

# Wildcard patterns to skip (lowercased). Supports endswith-style matching.
SKIP_PATTERNS = [
    "*tree seeds",
]