'''
SKIP_FIELDS maps item names to specific infobox fields that should be excluded from comparison.
This is used to suppress false mismatches caused by hidden or hardcoded in-game values
that are not present in the JSON source data.
'''
SKIP_FIELDS = {
    "Sugar": ["restores"], # Sugar has a hidden -10hp that isn't in the data files.
    "Sandy Ice Cream": ["restores"], # Sandy Ice Cream has a hidden -5hp that isn't in the data files.
    "Sandstone Sashimi": ["restores"], # Has a hidden -10hp that isn't in the data files.
    "The Prehistoric Special": ["restores"], # Has a hidden -10hp that isn't in the data files.

    "Elven Health Book": ["statInc"], # The hp increase isn't in the data files but hardcoded somewhere.
    "Small Mana Tome": ["statInc"], # The mp increase isn't in the data files but hardcoded somewhere.
    
    "Fire Sprite": ["sell", "currency"],        # These aren't real items
    "Water Sprite": ["sell", "currency"],       # These aren't real items
    "Rock Sprite": ["sell", "currency"],        # These aren't real items
    "Wind Sprite": ["sell", "currency"],        # These aren't real items
    "White Baby Dragon": ["sell", "currency"],  # These aren't real items
    "Squirrel": ["sell", "currency"],           # These aren't real items

    "Tier 1 Sewer Barn Permit": ["hearts"],
    "Tier 2 Sewer Barn Permit": ["hearts"],
    "Tier 3 Sewer Barn Permit": ["hearts"],
    "Sewer Barn Access Key": ["hearts"],
    "Kingly Ticket": ["hearts"],
    "Economy Ticket": ["hearts"],
    "First Class Ticket": ["hearts"],
    "Spring Token": ["hearts"],
    "Summer Token": ["hearts"],
    "Fall Token": ["hearts"],
    "Winter Token": ["hearts"],

    "Coins": ["sell", "stack"],                 # Bad data
    "Tickets": ["sell", "stack"],               # Bad data
    "Mana Orbs": ["sell", "stack"],             # Bad data
}

'''
SKIP_ITEMS are pages we want to ignore.
'''
SKIP_ITEMS = [
    "Ocean Treasure Chest",
    "aegis",
    "adamant ore node",
    "alchemy bundle",
    "alien chair",
    "amethystnode",
    "ancient nel'varian text",
    "angler's box",
    "animal feeder",
    "anne chest",
    "archeology bundle",
    "arena chest",
    "baker's box",
    "bars bundle",
    "bernard's big bundle",
    "berry forageable",
    "beryl node",
    "black bottle cap",
    "blacksmith's box",
    "blue wooden l table",
    "bones bundle",
    "bonus attack damage",
    "bonus movement speed",
    "bonus spell damage",
    "bowed gift",
    "breakable pot",
    "breath stone",
    "bridge customization kit",
    "brinestone deeps classic record",
    "brinestone deeps general store record",
    "brinestone teleportation spell",
    "brinestonedeepsrock1x1_green",
    "brinestonedeepsrock1x1_grey",
    "brinestonedeepsrock1x1_yellow",
    "brinestonedeepsrock2x2_green",
    "brinestonedeepsrock2x2_grey",
    "brinestonedeepsrock2x2_yellow",
    "broken branches",
    "broken cobblestone",
    "bundle aquarium bigtank",
    "bundle aquarium fall",
    "bundle aquarium nelvari",
    "bundle aquarium spring",
    "bundle aquarium summer",
    "bundle aquarium winter",
    "bundle aquarium withergate",
    "burlap gift",
    "cardboard chest",
    "catch of the day",
    "catherine chest",
    "celestial runes gift",
    "ceremonial dagger",
    "citrine node",
    "claude apple tree",
    "claude chest",
    "combat bundle",
    "common fish",
    "cotton candy",
    "crop totem",
    "darius chest",
    "darkness crop",
    "darkness weed",
    "dead crop",
    "dead heavystone node",
    "dead stone node",
    "deep conspiracy board",
    "deep jaws",
    "diamondnode",
    "dizzite node",
    "dizzy rock node",
    "donovan chest",
    "dragon chest",
    "dragon chest one time",
    "dragon trap",
    "dreamy pet chest",
    "driftwood gift",
    "duelist's box",
    "dungeon chest",
    "dynus altar rareitems",
    "earth crystal forageable",
    "elven blueberry tree",
    "elven eyes",
    "elven hardwood tree",
    "elven heavystone node",
    "elven peach tree",
    "elven raspberry tree",
    "elven stone node",
    "elven strawberry tree",
    "elemental tap",
    "epic fish",
    "expensive gift",
    "expert crafter",
    "explorer's box",
    "fall crops bundle",
    "fallen log",
    "fancy gift",
    "farmer's box",
    "farming slot maker",
    "fighter's crest",
    "fire beam",
    "fire crystal forageable",
    "fire fruit seeds",
    "firebolt gift",
    "fishing bundle",
    "flames and ashes chest",
    "floral gift",
    "floor 1 dungeon key",
    "floor 10 dungeon key",
    "floor 15 dungeon key",
    "floor 20 dungeon key",
    "floor 25 dungeon key",
    "floor 5 dungeon key",
    "flowers bundle",
    "forageable chest",
    "forest sleeping monster",
    "forked road sleeping monster",
    "four region's thank you letter",
    "gembundle",
    "geode bundle",
    "geode muncher",
    "golden bundle",
    "golden record player chest",
    "gorwin's gift",
    "hard deadwood tree",
    "havenitenode",
    "heavystone node",
    "homemade gift",
    "hot chocolate machine",
    "house customization kit",
    "hungry slime bundle one",
    "hungry slime bundle three",
    "hungry slime bundle two",
    "impeccable gift",
    "ink puddle",
    "iris chest",
    "jun chest",
    "kai chest",
    "karish chest",
    "kitty chest",
    "kitty gift",
    "krusty rock node",
    "lapis node",
    "leaf gift",
    "legendary fish",
    "letter from lucia",
    "liam chest",
    "little girl's gift",
    "lucia chest",
    "lucius chest",
    "lucius record",
    "lynn chest",
    "mailbox demolition kit",
    "mana tome forageable",
    "manabundle",
    "mermaid's touch",
    "miracle",
    "miyeon chest",
    "money bag forageable",
    "moneybundle",
    "monster furniture table",
    "moon print gift",
    "music note gift",
    "nathaniel chest",
    "nel'vari teleportation spell",
    "nelvari farming bundle",
    "nelvari mines bundle",
    "nelvari temple books bundle",
    "newspaper gift",
    "oozing creepy window",
    "orange gilded floor tile",
    "orange pepper flakes",
    "orb",
    "orchard farmer's box",
    "orchard honey maker",
    "orchard jam maker",
    "painted gift",
    "pet baby dragon chest",
    "pet baby tiger chest",
    "peter bomb fish bundle",
    "pile of snow",
    "pilot targeting window",
    "pirate life chest",
    "pirated thick coral display",
    "pixie dust",
    "player farm nelvari stone node",
    "player farm stone node",
    "player farm withergate stone node",
    "poorly wrapped gift",
    "powerful sun display",
    "primal nature",
    "pyre",
    "quest bounty",
    "rancher's box",
    "rare fish",
    "red wrapped gift",
    "rex's cap",
    "rock 'n' roll chest",
    "rock1b",
    "rock1c",
    "rock1d",
    "rock2b",
    "rock2c",
    "rock2d",
    "rock3b",
    "rock3c",
    "rock3d",
    "rock4b",
    "rock4c",
    "rock4d",
    "rock5b",
    "rock5c",
    "rock5d",
    "rock6b",
    "rock6c",
    "rock6d",
    "rock7b",
    "rock7c",
    "rock7d",
    "rock fruit seeds",
    "royalty's box",
    "rubynode",
    "sapphirenode",
    "seaweed node",
    "seaweed wrapped gift",
    "shang chest",
    "shadow rush",
    "sharp dragon scale rock",
    "shard rock large",
    "shard rock medium",
    "shard rock small",
    "smoke",
    "snaccoon block farm",
    "snaccoon costume chest",
    "snaccoon town hall",
    "snacoon beach bridge",
    "snacoon beach pier",
    "snacoon beach transition",
    "snacoon farm",
    "snacoon foresta",
    "snacoon forestf",
    "snacoon mines20a",
    "snacoon mines40a",
    "snacoon nelvari",
    "snacoon quarry",
    "snacoon quarry transition",
    "snacoon right outskirts",
    "snacoon wheat field",
    "snow yeti chest",
    "snowy observation window",
    "sock kites",
    "solon order form",
    "soup bundle",
    "sparkling gear chest",
    "spellcaster's box",
    "spring crops bundle",
    "squeaky clean chest",
    "summer crops bundle",
    "sweet mounts chest",
    "tea temple chest",
    "tiger print gift",
    "traditional gift",
    "uncommon fish",
    "vaan chest",
    "vivi chest",
    "water crystal forageable",
    "water fruit seeds",
    "wheat grass juice",
    "white gift",
    "wicked mounts chest",
    "wind orb",
    "winter crops bundle",
    "withergate farming bundle",
    "withergate mines bundle",
    "wornhardt chest",
    "xyla chest",
    "zaria chest",
    "zaria's bucket",
    "zaria's empty bucket",
    "emerald elegance chest",
    "lynn anvil",
    "lynn's pickaxe",
    "seal of sun haven",
    "snow cone machine",
    "ticket",
    "warehouse",
    "snaccoon right outskirts winter",
    "town north entrance sleeping monster",
    "sparkling dragon scale rock",
]

SKIP_PATTERNS = [
    "* tree seeds",
    "* bundle",
    "*teleportation spell",
    "*onetimechest",
    "* node",
    "*minerock*",
    "largerock*",
    "alien chair*",
    "*bridge decor",
    "*sombasu's fortune*",
    "crate red-crystal*",
    "crate blue-crystals*",
    "crate purple-crystals*",
    "*foliage*",
    "recurringchest*",
    "hiddenchest*",
    "*(old)",
]
