"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://sunhaven.wiki.gg/wiki/Sun_Haven_Wiki
  name = sunhaven

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'sunhaven'
    langs = {
        'en': 'sunhaven.wiki.gg',
    }

    def scriptpath(self, code):
        return {
            'en': '',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
        }[code]
